### PR TITLE
Updates ES version and expose ES port

### PR DESCRIPTION
**Pull request by albertininm**
Fixes https://github.com/wedeploy-examples/elasticsearch-example/issues/6

### CODE REVIEW

**Comment by cirocosta** [comment]
Hey,

Maybe I'm missing something, but I'd say exposing the elasticsearch port without any authentication method is highly discouraged given that it'd give full access to anyone on the internet: `curl -XDELETE <service_url>/_all` and then all your indices are gone.

thx!

**Comment by cirocosta** [comment]
*(btw, a quick tip: if you want a quick way of formatting json, you can pipe your json straight to `python -m "json.tool"` and then you'll get it pretty formatted)*

**Comment by albertininm** [comment]
@cirocosta I can remove it, but it is confusing for users don't see anything when accessing their `URL`.

**Comment by zenorocha** [comment]
I agree with @cirocosta, but since this is just an example we can keep it. Thanks @albertmourato!

**Pull request merged**
